site_name: MacServer Documentation
site_url: https://andrewbreyen.github.io/MacServer-Documentation/
nav:
    - Home: index.md
    - Setup:
      - 'First Time Setup': 'setup/first-time-setup.md'
      - 'macOS Settings': 'setup/macos-settings.md'
      - 'Jumpcloud': 'setup/jumpcloud.md'
    - Server Apps:
      - 'macOS Server': 'server-apps/macos-server.md'
      - 'TeamViewer': 'server-apps/teamviewer.md'
      - 'Jellyfin': 'server-apps/jellyfin.md'
      - 'Homebridge': 'server-apps/homebridge.md'
      - 'Scrypted': 'server-apps/scrypted.md'
      - 'Node-RED': 'server-apps/node-red.md'
      - 'Pihole': 'server-apps/pihole.md'
      - 'Tdarr': 'server-apps/tdarr.md'
    - Hardware:
      - 'Hardware': 'hardware/hardware.md'
    - Troubleshooting:
      - 'Reboot': 'troubleshooting/reboot.md'
      - 'Live TV Guide Data Issues': 'troubleshooting/live-tv-data-issues.md'
      - 'Smart Devices showing as “No Response”/Orange Exclamation mark': 'troubleshooting/no-response-homekit.md'
      - 'Network Change: Smart Home Devices': 'troubleshooting/network-change-smart-home.md'
theme:
  name: material
  logo: img/macmini-icon.png
  favicon: img/macmini-icon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys