name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - "main"

jobs:
  builddeploy:
    name: ghpages-build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install requirements
        run: python3 -m pip install -r requirements.txt

      - name: Deploy 🚀
        run: python3 -m mkdocs gh-deploy --force --strict
      # - name: Checkout
      #   uses: actions/checkout@v2

      # - name: Build
      #   uses: Tiryoh/actions-mkdocs@v0
      #   with:
      #     mkdocs_version: "latest"
      #     requirements: "requirements.txt"
      #     configfile: "mkdocs.yml"

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./site