name: Lint Markdown

on:
  push:
    branches:
      - "main"

jobs:
  builddeploy:
    name: lint-markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: prettier
        uses: actionsx/prettier@v2
        with:
          # prettier CLI arguments.
          args: --check "**/*.md"

      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: "**/*.md"

      # - name: Post to a Slack channel
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     # Slack channel ID where the message will be posted. Needed if using a bot token
      #     channel-id: "C05JB2CA4SE"
      #     # Message to post into Slack. Needed if using a bot token
      #     payload: |
      #       {
      #         "text": "MacSetup build and deploy result:${{ needs.build.result }}",
      #         "blocks": [
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "MacSetup build and deploy result:\n${{ needs.build.result }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      #             }
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
