name: Build and Deploy using Vercel

on:
  push:
    paths:
      - docs/**
      - mkdocs.yml
      - .github/workflows/vercel-deploy.yml
    
  workflow_dispatch:

jobs:
    build:
      name: Build (Tiryoh/actions-mkdocs)
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Build
          uses: Tiryoh/actions-mkdocs@v0
          with:
            mkdocs_version: "latest"
            requirements: "requirements.txt"
            configfile: "mkdocs.yml"
            
        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            path: site
            name: site

    deploy:
      name: Deploy Vercel (test/prod)
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test'
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Download Artifact
          uses: actions/download-artifact@v3
          with:
            name: site
            path: site
            
        - name: Deploy Documentation - Test
          if: github.ref == 'refs/heads/test'
          run: npx vercel --yes --cwd site --token ${{ secrets.VERCEL_TOKEN }} --prod=false
          env:
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
            
        - name: Deploy Documentation - Prod
          if: github.ref == 'refs/heads/main'
          run: npx vercel --yes --cwd site --token ${{ secrets.VERCEL_TOKEN }} --prod
          env:
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}